##### 2.3.3 自定义异常类

自定义业务异常类，封装可预知的业务异常（权限不足、资源不存在、邮件发送失败等）。

```java
@Getter
public class BusinessException extends RuntimeException{
    private int code;
    private String msg;

    public BusinessException(HttpCodeEnum httpCodeEnum) {
        super(httpCodeEnum.getMsg());
        this.code = httpCodeEnum.getCode();
        this.msg = httpCodeEnum.getMsg();
    }

    public BusinessException(HttpCodeEnum httpCodeEnum, String msg) {
        super(httpCodeEnum.getMsg());
        this.code = httpCodeEnum.getCode();
        this.msg = httpCodeEnum.getMsg() + ": " + msg;
    }
}
```

Java中的异常类层次结构可以概括为：
```
Throwable
├── Error                        // 不可恢复的严重错误
│   ├── OutOfMemoryError
│   └── StackOverflowError
└── Exception                   // 可处理的异常
    ├── Checked Exception       // 受检异常（Exception除RuntimeException的其他子类）
    │   ├── IOException
    │   ├── SQLException
    │   └── FileNotFoundException
    └── RuntimeException        // 非受检异常（等价RuntimeException）
        ├── NullPointerException
        ├── IndexOutOfBoundsException
        ├── IllegalArgumentException
        └── ArithmeticException
```

###### `Exception`和`Error`

- `Exception`：表示程序运行过程中可以处理的异常，可以通过`try-catch`语句捕获并处理
- `Error`：表示程序运行过程中不可处理的严重错误，如内存溢出等，尽管可以捕获，但通常不建议处理

###### `Checked Exception`和`RuntimeException`
- `Checked Exception`：`Exception`的子类中，除了`RuntimeException`，其余的全是受检异常。在编译时必须通过`try-catch`处理或在方法签名中声明抛出
- `RuntimeException`：非受检异常，编译器不会强制要求处理，可以在运行时抛出，通常表示程序逻辑错误

###### `Throwable`

`Throwable` 是所有`Error`和的根类。常用属性和方法如下：

```java
public class Throwable {
    private String detailMessage; // 异常的详细信息
    private Throwable cause;       // 引发当前异常的原因（链式异常）
    private StackTraceElement[] stackTrace; // 异常发生时的堆栈轨迹

    public String getMessage() { ... }
    public String toString() { ... }
    public StackTraceElement[] getStackTrace() { ... }
    public void printStackTrace() { ... }
}
```

###### `try-catch-finally`

当`try`语句和`finally`语句中都有`return`时，`try`语句块中的`return`会被忽略。`finally`中的代码并不一定会执行，例如当在`try`或`catch`中调用了`System.exit()`方法，或者程序所在的线程死亡等情况。

###### `try-with-resources`

适用于任何实现`java.lang.AutoCloseable`接口的资源（`java.io.Closeable`也是它的一个子接口）

```java
try (Scanner scanner = new Scanner(new File("test.txt"))) {
    while (scanner.hasNext()) {
        System.out.println(scanner.nextLine());
    }
} catch (FileNotFoundException e) {
    e.printStackTrace();
}
```